version: 1

map: ../../maps/warehouse_5x4.yaml
params: ../../params/default.yaml

robots:
  - {id:  0, start:  0, goal: 15}
  - {id:  1, start:  1, goal: 16}
  - {id:  2, start:  3, goal: 18}
  - {id:  3, start:  4, goal: 19}
  - {id:  4, start: 15, goal:  0}
  - {id:  5, start: 16, goal:  1}
  - {id:  6, start: 18, goal:  3}
  - {id:  7, start: 19, goal:  4}
  - {id:  8, start:  5, goal:  9}
  - {id:  9, start:  9, goal:  5}
  - {id: 10, start: 10, goal: 14}
  - {id: 11, start: 14, goal: 10}
  - {id: 12, start:  2, goal: 17}
  - {id: 13, start: 17, goal:  2}
