set(_AMENT_PACKAGE_NAME "mrs_msgs")
set(mrs_msgs_VERSION "1.1.0")
set(mrs_msgs_MAINTAINER "Changju Hwang <hchju23257@gmail.com>")
set(mrs_msgs_BUILD_DEPENDS "action_msgs")
set(mrs_msgs_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(mrs_msgs_BUILD_EXPORT_DEPENDS "action_msgs")
set(mrs_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(mrs_msgs_EXEC_DEPENDS "rosidl_default_runtime" "action_msgs")
set(mrs_msgs_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(mrs_msgs_GROUP_DEPENDS )
set(mrs_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(mrs_msgs_DEPRECATED "")
set(mrs_msgs_EXPORT_TAGS)
list(APPEND mrs_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
