version: 1

map: ../../maps/square.yaml
params: ../../params/default.yaml

robots:
  - id: R0
    start: 0
    home: 0
  - id: R1
    start: 3
    home: 3

scenario:
  replan_policy: replan_on_assignment
  events:
    - id: e0
      type: assign_goal
      robot: R0
      goal: 3
      when:
        type: at_start
    - id: e1
      type: assign_goal
      robot: R1
      goal: 0
      when:
        type: at_start
    - id: e2
      type: assign_goal
      robot: R0
      goal: 0
      when:
        type: on_robot_idle
        robot: R0
    - id: e3
      type: assign_goal
      robot: R1
      goal: 3
      when:
        type: on_robot_idle
        robot: R1
