set(_AMENT_PACKAGE_NAME "mrs_trajopt")
set(mrs_trajopt_VERSION "0.1.0")
set(mrs_trajopt_MAINTAINER "Changju Hwang <hchju23257@gmail.com>")
set(mrs_trajopt_BUILD_DEPENDS "mrs_msgs" "mrs_core" "rclcpp" "pluginlib" "geometry_msgs" "nav_msgs" "sensor_msgs")
set(mrs_trajopt_BUILDTOOL_DEPENDS "ament_cmake")
set(mrs_trajopt_BUILD_EXPORT_DEPENDS "mrs_msgs" "mrs_core" "rclcpp" "pluginlib" "geometry_msgs" "nav_msgs" "sensor_msgs")
set(mrs_trajopt_BUILDTOOL_EXPORT_DEPENDS )
set(mrs_trajopt_EXEC_DEPENDS "mrs_msgs" "mrs_core" "rclcpp" "pluginlib" "geometry_msgs" "nav_msgs" "sensor_msgs")
set(mrs_trajopt_TEST_DEPENDS "ament_lint_auto")
set(mrs_trajopt_GROUP_DEPENDS )
set(mrs_trajopt_MEMBER_OF_GROUPS )
set(mrs_trajopt_DEPRECATED "")
set(mrs_trajopt_EXPORT_TAGS)
list(APPEND mrs_trajopt_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
