# corridor map
#
#  Zone A          Zone B
#  0(0,2)-1(1,2)   5(5,2)-6(6,2)
#  |      |        |      |
#  2(0,0)-3(1,0)   4(5,0)-7(6,0)
#           |      |
#    Corridor1: 3-8-9-4
#
#  1-10-11-5

graph:
  vertices:
    - id: 0
      x: 0.0
      y: 2.0
    - id: 1
      x: 1.0
      y: 2.0
    - id: 2
      x: 0.0
      y: 0.0
    - id: 3
      x: 1.0
      y: 0.0
    - id: 4
      x: 5.0
      y: 0.0
    - id: 5
      x: 5.0
      y: 2.0
    - id: 6
      x: 6.0
      y: 2.0
    - id: 7
      x: 6.0
      y: 0.0
    - id: 8
      x: 2.5
      y: 0.0
    - id: 9
      x: 3.5
      y: 0.0
    - id: 10
      x: 2.5
      y: 2.0
    - id: 11
      x: 3.5
      y: 2.0
  edges:
    - [0, 1]
    - [1, 3]
    - [3, 2]
    - [2, 0]
    - [4, 5]
    - [5, 6]
    - [6, 7]
    - [7, 4]
    - [3, 8]
    - [8, 9]
    - [9, 4]
    - [1, 10]
    - [10, 11]
    - [11, 5]
