set(_AMENT_PACKAGE_NAME "mrs_core")
set(mrs_core_VERSION "0.1.0")
set(mrs_core_MAINTAINER "Changju Hwang <hchju23257@gmail.com>")
set(mrs_core_BUILD_DEPENDS "mrs_msgs")
set(mrs_core_BUILDTOOL_DEPENDS "ament_cmake")
set(mrs_core_BUILD_EXPORT_DEPENDS "mrs_msgs")
set(mrs_core_BUILDTOOL_EXPORT_DEPENDS )
set(mrs_core_EXEC_DEPENDS "mrs_msgs")
set(mrs_core_TEST_DEPENDS "ament_lint_auto")
set(mrs_core_GROUP_DEPENDS )
set(mrs_core_MEMBER_OF_GROUPS )
set(mrs_core_DEPRECATED "")
set(mrs_core_EXPORT_TAGS)
list(APPEND mrs_core_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
